[example]
id = "317cac9d-2f3d-46cf-ba8d-273d385bf197"
auth = false

[secure-example]
id = "87d42e91-7db9-42e8-a4eb-d3be46c84b02"
auth = true
password = "password"

[js-example]
id = "13052600-4a29-4396-ace8-18feeb109f08"
auth = false
js = true