[example]
id = "41ca6d35-c8bf-4d66-80ad-04e3d6403ffe"
name = "Example"
description = "An example userscript"
auth = false
script = "example.ts"

[secure-example]
id = "4a7fea25-ced0-4793-9823-63f392a8caf4"
name = "Secure example"
description = "A secure example userscript"
auth = true
script = "secure-example.ts"