services:
  sandman:
    image: ghcr.io/selfagency/sandman:latest
    ports:
      - '3000:3000'
      - '8001:8001'
    volumes:
      - ./config.toml:/app/config.toml
      - ./data:/app/data
      - ./scripts:/app/scripts
    environment:
      - NODE_ENV=${NODE_ENV}
      - LOG_KEY=${LOG_KEY}
