services:
  sandman:
    image: 'ghcr.io/selfagency/sandman:latest'
    networks:
      - sandman
    ports:
      - '3000:3000'
      - '8001:8001'
    volumes:
      - './.env:/app/.env'
      - './config.toml:/app/config.toml'
      - './data:/app/data'
      - './scripts:/app/scripts'
    healthcheck:
      test: curl --fail http://localhost:3000/health
    environment:
      - 'NODE_ENV=${NODE_ENV}'
      - 'LOG_KEY=${LOG_KEY}'
      - 'OUTDIR=${OUTDIR}'

networks:
  sandman:
    driver: bridge
